[package]
name = "webcompiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"

[features]
lol_alloc = ["dep:lol_alloc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-html = "0.2.2"
anyhow = "1.0.99"
base64 = "0.22.1"
cfg-if = "1.0.1"
colored = "3.0.0"
console_error_panic_hook = "0.1.7"
lol_alloc = { version = "0.4.1", optional = true }
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
shulkerscript = { version = "0.1.0", default-features = false, features = ["serde", "shulkerbox"] }
toml = "0.9.5"
wasm-bindgen = "0.2.100"
zip = { version = "4.3.0", default-features = false, features = ["deflate"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false